---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new VPC, using best practices.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

Parameters:
    Project:
        Description: 'Project name this VPC is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this VPC'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the VPC will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

Resources:
    VPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: '10.0.0.0/16'
            EnableDnsSupport: 'false'
            EnableDnsHostnames: 'false'
            InstanceTenancy: 'dedicated'
            Tags:
                - Key: 'Name'
                  Value:
                      Ref: 'Project'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'VPC for project', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    PublicSubnetZoneA:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '0'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.10.0/24'
            MapPublicIpOnLaunch: 'True'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Public Zone A'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Public for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    PrivateSubnetZoneA:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '0'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.20.0/24'
            MapPublicIpOnLaunch: 'False'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Private Zone A'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Private for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    PublicSubnetZoneB:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '1'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.30.0/24'
            MapPublicIpOnLaunch: 'True'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Public Zone B'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Public for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    PrivateSubnetZoneB:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '1'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.40.0/24'
            MapPublicIpOnLaunch: 'False'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Private Zone B'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Private for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

Outputs:
    VPCID:
        Description: 'VPC ID'
        Value:
            Ref: VPC
        Export:
            Name: !Join [ ':', [ !Ref 'AWS::StackName', VPCID ] ]
    PublicSubnetA:
        Description: 'Zone A Public Subnet ID'
        Value:
            Ref: PublicSubnetZoneA
        Export:
            Name: !Join [ ':', [ !Ref 'AWS::StackName', PublicSubnetA ] ]
    PrivateSubnetA:
        Description: 'Zone A Private Subnet ID'
        Value:
            Ref: PrivateSubnetZoneA
        Export:
            Name: !Join [ ':', [ !Ref 'AWS::StackName', PrivateSubnetA ] ]
    PublicSubnetB:
        Description: 'Zone B Public Subnet ID'
        Value:
            Ref: PublicSubnetZoneB
        Export:
            Name: !Join [ ':', [ !Ref 'AWS::StackName', PublicSubnetB ] ]
    PrivateSubnet2:
        Description: 'Zone B Private Subnet ID'
        Value:
            Ref: PrivateSubnetZoneB
        Export:
            Name: !Join [ ':', [ !Ref 'AWS::StackName', PrivateSubnetB ] ]
