---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new VPC, using best practices.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

Parameters:
    Project:
        Description: 'Project name this VPC is has been created for'
        Type: 'String'
        Default: 'CHANGE ME'

    Creator:
        Description: 'Tool or person creating this VPC'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the VPC will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

Mappings:
    VPCRanges:
        subnets:
            PublicSubnetZone1: '10.0.10.0/24'
            PrivateSubnetAZ1: '10.0.20.0/24'
            PublicSubnetAZ2: '10.0.30.0/24'
            PrivateSubnetAZ2: '10.0.40.0/24'

Resources:
    VPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: '10.0.0.0/16'
            EnableDnsSupport: 'false'
            EnableDnsHostnames: 'false'
            InstanceTenancy: 'dedicated'
            Tags:
                - Key: 'Name'
                  Value:
                      Ref: 'Project'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'VPC for project', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    PublicSubnetZone1:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '0'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.10.0/24'
            MapPublicIpOnLaunch: 'True'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Public Zone 1'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Public for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'
    PrivateSubnetZone1:
        Type: 'AWS::EC2::Subnet'
        Properties:
            AvailabilityZone:
                Fn::Select:
                - '0'
                - Fn::GetAZs:
                    Ref: AWS::Region
            CidrBlock: '10.0.20.0/24'
            MapPublicIpOnLaunch: 'False'
            VpcId:
                Ref: VPC
            Tags:
                - Key: 'Name'
                  Value: 'Private Zone 1'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value:
                      'Fn::Join': [ ' ', [ 'Private for', !Ref Project ] ]
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'


Outputs:
    VPCID:
        Description: 'VPC ID'
        Value:
            Ref: VPC
    PublicSubnet1:
        Description: 'Zone 1 Public Subnet ID'
        Value:
            Ref: PublicSubnetZone1
    PrivateSubnet1:
        Description: 'Zone 1 Private Subnet ID'
        Value:
            Ref: PrivateSubnetZone1
